const root = document.querySelector('#app');
const state = { token: localStorage.token, role: localStorage.role, page: 'dashboard', query: { page: 1, limit: 10 } };
const TEAMS = ['L2-Network','L2-Application','L3-Database','Security','L1-Hardware','L1-General'];
const esc = (s='') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pct = v => v == null ? '—' : `${Math.round(Number(v) * 100)}%`;
const riskClass = r => String(r || '').toLowerCase() === 'high' ? 'risk-high' : 'risk-low';
async function api(path, opt={}) {
  const r = await fetch('/api/v1' + path, { ...opt, headers: { 'Content-Type':'application/json', ...(state.token ? { Authorization:`Bearer ${state.token}` } : {}) } });
  const d = await r.json().catch(() => ({}));
  if (r.status === 401) { logout(); throw Error('Your session expired.'); }
  if (!r.ok) throw Error(d.error?.message || 'Request failed.');
  return d;
}
function logout(){ localStorage.clear(); state.token=state.role=null; render(); }
const canEdit = () => ['admin','support_agent'].includes(state.role);
function nav(){
  let items=['dashboard','tickets','predictions'];
  if(['admin','analyst'].includes(state.role)) items.push('analytics');
  if(state.role==='admin') items.push('jira','users');
  const icon={dashboard:'◫',tickets:'▤',predictions:'✦',analytics:'◒',jira:'↔',users:'♙'};
  return `<aside class="nav"><div class="brand"><span class="brand-mark">AI</span><div><strong>Ticket Intelligence</strong><small>${esc(state.role)}</small></div></div><div class="nav-links">${items.map(x=>`<button data-page="${x}" class="${state.page===x?'active':''}"><span>${icon[x]}</span>${x}</button>`).join('')}</div><button id="logout" class="logout">Log out</button></aside>`;
}
function badge(text, cls=''){ return `<span class="badge ${cls}">${esc(text)}</span>`; }
function table(ts){
  return `<table class="table"><thead><tr><th>Ticket</th><th>Priority</th><th>Status</th><th>Team</th></tr></thead><tbody>${ts.length?ts.map(t=>`<tr><td><button class="link-btn open" data-id="${t.id}">${esc(t.jira_issue_key||'#'+t.id)}</button><div class="cell-sub">${esc(t.summary)}</div></td><td>${badge(t.priority)}</td><td>${esc(t.status)}</td><td>${esc(t.assigned_team||'Unassigned')}</td></tr>`).join(''):'<tr><td colspan="4">No tickets match these filters.</td></tr>'}</tbody></table>`;
}
function query(){ const q=state.query, p=new URLSearchParams({limit:q.limit,offset:(q.page-1)*q.limit}); for(const k of ['priority','status','team','search']) if(q[k]) p.set(k,q[k]); return '/tickets?'+p; }
async function dashboard(){
  const d=await api('/tickets?limit=6');
  const a=(await api('/analytics').catch(()=>({analytics:{}}))).analytics;
  return `<section class="hero"><div><span class="eyebrow">AI OPERATIONS CONSOLE</span><h1>Ticket intelligence, at a glance.</h1><p>Route tickets with text-aware AI, surface SLA risk, and keep a human in the loop.</p></div><div class="model-card"><span class="model-dot"></span><div><strong>triage-v1.0</strong><small>Routing + SLA models</small></div></div></section><div class="cards"><div class="stat"><small>Total tickets</small><div class="metric">${a.total_tickets??d.total}</div></div><div class="stat"><small>Open tickets</small><div class="metric">${a.open_tickets??'—'}</div></div><div class="stat"><small>AI predictions</small><div class="metric">${a.prediction_count??'—'}</div></div><div class="stat"><small>Human overrides</small><div class="metric">${a.override_count??0}</div></div></div><section class="panel"><div class="section-head"><div><h2>Recent tickets</h2><p>Latest operational activity.</p></div><button class="ghost" data-page="tickets">View all</button></div>${table(d.tickets)}</section>`;
}
async function tickets(){
  const d=await api(query()), q=state.query, pages=Math.max(1,Math.ceil(d.total/q.limit));
  return `<section class="top"><div><span class="eyebrow">WORK QUEUE</span><h1>Tickets</h1><p>${d.total} results</p></div>${canEdit()?'<button id="create">＋ Create ticket</button>':''}</section><form id="filters" class="toolbar panel"><label>Search<input name="search" value="${esc(q.search||'')}" placeholder="Key or summary"></label><label>Priority<select name="priority"><option value="">All</option>${['High','Medium','Low'].map(x=>`<option ${q.priority===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<input name="status" value="${esc(q.status||'')}" placeholder="open"></label><label>Team<input name="team" value="${esc(q.team||'')}" placeholder="L2-Network"></label><button>Apply filters</button></form><section class="panel table-panel">${table(d.tickets)}<div class="pager"><button id="prev" class="ghost" ${q.page===1?'disabled':''}>Previous</button><span>Page ${q.page} of ${pages}</span><button id="next" class="ghost" ${q.page>=pages?'disabled':''}>Next</button></div></section><section id="action" aria-live="polite"></section>`;
}
function ticketForm(t={}){
  return `<form id="ticket-form" class="form panel"><div class="section-head"><div><h2>${t.id?'Update':'Create'} ticket</h2><p>Use the same fields consumed by the Stage 1 AI pipeline.</p></div></div><label>Summary<input name="summary" value="${esc(t.summary||'')}" required></label><label>Description<textarea name="description" placeholder="Describe the customer issue clearly...">${esc(t.description||'')}</textarea></label><div class="form-grid"><label>Priority<select name="priority">${['High','Medium','Low'].map(x=>`<option ${t.priority===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Issue type<select name="issue_type">${['Network','Application','Database','Access','Hardware','General'].map(x=>`<option ${t.issue_type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Project<input name="project" value="${esc(t.project||'General')}"></label><label>Component<input name="component" value="${esc(t.component||'General')}"></label><label>Customer tier<select name="customer_tier">${['Standard','Business','Enterprise'].map(x=>`<option ${t.customer_tier===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Channel<select name="channel">${['Portal','Email','Chat','Phone'].map(x=>`<option ${t.channel===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Created hours<input type="number" min="0" step="0.1" name="created_hours" value="${t.created_hours??0}" required></label><label>Status<input name="status" value="${esc(t.status||'open')}"></label></div><label>Assigned team<input name="assigned_team" value="${esc(t.assigned_team||'')}" placeholder="Leave blank until AI triage"></label><button>${t.id?'Save changes':'Create & triage'}</button><output></output></form>`;
}
function aiCard(p){
  if(!p) return `<section class="ai-card empty"><span class="eyebrow">AI TRIAGE</span><h2>No prediction yet</h2><p>Run triage to see the recommended team, SLA risk, and explanation.</p></section>`;
  const feedback=p.feedback?.[0];
  return `<section class="ai-card"><div class="ai-head"><div><span class="eyebrow">AI TRIAGE · ${esc(p.model_version)}</span><h2>${esc(p.recommended_team)}</h2><p>Recommended resolving team</p></div>${badge(p.predicted_risk+' SLA risk',riskClass(p.predicted_risk))}</div><div class="ai-metrics"><div><small>Route confidence</small><strong>${pct(p.routing_confidence)}</strong></div><div><small>SLA breach probability</small><strong>${pct(p.sla_probability)}</strong></div></div><div class="explain"><h3>Why the model chose this</h3><ul>${(p.explanation||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${feedback?`<div class="feedback-state ${feedback.decision==='override'?'overridden':'accepted'}"><strong>${feedback.decision==='override'?'Human override':'Accepted by agent'}</strong><span>${feedback.decision==='override'?`Assigned to ${esc(feedback.corrected_team)}`:`Assigned to ${esc(p.recommended_team)}`}</span></div>`:''}${canEdit()&&!feedback?`<div class="ai-actions"><button class="accept" data-feedback="accept" data-prediction="${p.id}">✓ Accept recommendation</button><button class="ghost" data-feedback="override" data-prediction="${p.id}">Override team</button></div><div id="feedback-action"></div>`:''}</section>`;
}
async function detail(id){
  const [r,h,fb]=await Promise.all([api('/tickets/'+id),api('/tickets/'+id+'/predictions'),api('/tickets/'+id+'/feedback').catch(()=>({feedback:[]}))]);
  const t=r.ticket, latest=h.predictions?.[0];
  return `<button id="back" class="ghost">← Back to tickets</button><section class="top detail-top"><div><span class="eyebrow">TICKET ${esc(t.jira_issue_key||'#'+t.id)}</span><h1>${esc(t.summary)}</h1><p>${esc(t.source)} · updated ${esc(t.updated_at)}</p></div>${canEdit()?'<button id="edit">Edit ticket</button>':''}</section><div class="detail-grid"><article class="panel"><div class="section-head"><div><h2>Ticket details</h2><p>Prediction uses only information available at triage time.</p></div>${badge(t.priority)}</div><p class="description">${esc(t.description||'No description')}</p><div class="facts"><div><small>Status</small><strong>${esc(t.status)}</strong></div><div><small>Current team</small><strong>${esc(t.assigned_team||'Unassigned')}</strong></div><div><small>Issue type</small><strong>${esc(t.issue_type||'General')}</strong></div><div><small>Project</small><strong>${esc(t.project||'General')}</strong></div><div><small>Component</small><strong>${esc(t.component||'General')}</strong></div><div><small>Customer tier</small><strong>${esc(t.customer_tier||'Standard')}</strong></div></div></article>${aiCard(latest)}</div><section class="panel"><div class="section-head"><div><h2>Human feedback</h2><p>Every accept/override is tied to a specific model prediction.</p></div></div>${fb.feedback?.length?`<div class="timeline">${fb.feedback.map(x=>`<div class="timeline-item"><div class="timeline-dot"></div><div><strong>${x.decision==='override'?'Override':'Accepted'} · ${esc(x.actor_email)}</strong><p>${x.decision==='override'?`AI route ${esc(x.predicted_team)} → ${esc(x.corrected_team)}`:`AI route ${esc(x.predicted_team)} accepted`}${x.comment?` · ${esc(x.comment)}`:''}</p><small>${esc(x.created_at)}</small></div></div>`).join('')}</div>`:'<p class="muted">No human feedback recorded yet.</p>'}</section><section class="panel"><div class="section-head"><div><h2>Prediction history</h2><p>Model outputs are retained for traceability.</p></div></div>${h.predictions?.length?h.predictions.map(x=>`<div class="prediction-row"><div><strong>${esc(x.recommended_team)}</strong><span>${esc(x.model_version)}</span></div><div>${badge(x.predicted_risk,riskClass(x.predicted_risk))} <span class="confidence">${pct(x.routing_confidence)} route · ${pct(x.sla_probability)} SLA</span></div></div>`).join(''):'<p class="muted">No stored predictions.</p>'}</section><section id="action"></section>`;
}
function overrideForm(predictionId){ return `<form id="override-form" class="form inline-form"><label>Assign to<select name="corrected_team">${TEAMS.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Comment<textarea name="comment" rows="2" maxlength="1000" placeholder="Why are you overriding the AI recommendation?"></textarea></label><button>Save override</button><output></output></form>`; }
async function predictions(){
  const d=await api('/tickets?limit=100'), all=[];
  for(const t of d.tickets){ const h=await api(`/tickets/${t.id}/predictions`); all.push(...h.predictions.map(x=>({...x,summary:t.summary,ticket_id:t.id}))); }
  return `<section class="top"><div><span class="eyebrow">MODEL ACTIVITY</span><h1>Prediction history</h1><p>Stored AI triage decisions across recent tickets.</p></div></section><section class="panel table-panel"><table class="table"><thead><tr><th>Ticket</th><th>Risk</th><th>SLA</th><th>Route</th><th>Confidence</th><th>Feedback</th></tr></thead><tbody>${all.length?all.map(x=>`<tr><td><button class="link-btn open" data-id="${x.ticket_id}">${esc(x.summary)}</button></td><td>${badge(x.predicted_risk,riskClass(x.predicted_risk))}</td><td>${pct(x.sla_probability)}</td><td>${esc(x.recommended_team)}</td><td>${pct(x.routing_confidence)}</td><td>${x.feedback?.[0]?esc(x.feedback[0].decision):'Pending'}</td></tr>`).join(''):'<tr><td colspan="6">No predictions stored.</td></tr>'}</tbody></table></section>`;
}
async function analytics(){
  const a=(await api('/analytics')).analytics; const fmt=o=>Object.entries(o||{}).map(([k,v])=>`<span class="chip">${esc(k)} <b>${v}</b></span>`).join('')||'<span class="muted">No data</span>';
  return `<section class="top"><div><span class="eyebrow">OPERATIONS ANALYTICS</span><h1>Performance snapshot</h1><p>Operational and human-in-the-loop signals.</p></div></section><div class="cards"><div class="stat"><small>Total tickets</small><div class="metric">${a.total_tickets}</div></div><div class="stat"><small>Predictions</small><div class="metric">${a.prediction_count}</div></div><div class="stat"><small>Accepted</small><div class="metric">${a.accept_count??0}</div></div><div class="stat"><small>Overrides</small><div class="metric">${a.override_count??0}</div></div></div><section class="split"><article class="panel"><h2>Priority distribution</h2><div class="chips">${fmt(a.by_priority)}</div></article><article class="panel"><h2>Team distribution</h2><div class="chips">${fmt(a.by_team)}</div></article></section><section class="panel"><h2>Status distribution</h2><div class="chips">${fmt(a.by_status)}</div></section>`;
}
async function jira(){ return `<section class="top"><div><span class="eyebrow">INTEGRATION</span><h1>Mock JIRA ingestion</h1><p>Local demo provider; no live JIRA credentials are used.</p></div></section><form id="jira" class="form panel"><label>Issue key<input name="key" placeholder="PROJ-101" required></label><label>Summary<input name="summary" required></label><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label><label>Created hours<input name="hours" type="number" min="0" required></label><button>Import ticket</button><output></output></form>`; }
async function users(){ const d=await api('/users'); return `<section class="top"><div><span class="eyebrow">ACCESS CONTROL</span><h1>User administration</h1><p>Role and account lifecycle management.</p></div></section><section class="split"><section class="panel"><table class="table"><thead><tr><th>Email</th><th>Role</th><th>State</th><th>Actions</th></tr></thead><tbody>${d.users.map(u=>`<tr><td>${esc(u.email)}</td><td><select data-role="${u.id}">${['admin','analyst','support_agent'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></td><td>${u.disabled?badge('Disabled','risk-high'):badge('Active')}</td><td><button class="ghost user" data-id="${u.id}" data-disabled="${u.disabled}">Save</button></td></tr>`).join('')}</tbody></table></section><form id="new-user" class="form panel"><h2>Create user</h2><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="8" required></label><label>Role<select name="role"><option>analyst</option><option>support_agent</option><option>admin</option></select></label><button>Create user</button><output></output></form></section>`; }
async function render(){
  if(!state.token){ root.innerHTML=`<section class="login"><div class="login-brand"><span class="brand-mark">AI</span></div><span class="eyebrow">TICKET INTELLIGENCE</span><h1>Route smarter. Respond faster.</h1><p>AI-assisted ticket routing and SLA risk prediction for support operations.</p><form id="login" class="form"><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" required></label><button>Sign in</button><output class="error"></output></form></section>`; document.querySelector('#login').onsubmit=login; return; }
  root.innerHTML=`<div class="shell">${nav()}<main class="content" aria-live="polite"><div class="loading">Loading…</div></main></div>`;
  try{document.querySelector('.content').innerHTML=await({dashboard,tickets,predictions,analytics,jira,users}[state.page]||dashboard)();bind();}catch(e){document.querySelector('.content').innerHTML=`<p class="error" role="alert">${esc(e.message)}</p>`;}
}
async function login(e){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.token=localStorage.token=d.access_token;state.role=localStorage.role=d.role;render();}catch(x){e.target.querySelector('output').textContent=x.message;}}
function bind(){
  document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.page=x.dataset.page;render();}); document.querySelector('#logout')?.addEventListener('click',logout);
  document.querySelectorAll('.open').forEach(x=>x.onclick=async()=>{document.querySelector('.content').innerHTML=await detail(x.dataset.id);bindDetail(x.dataset.id);});
  const f=document.querySelector('#filters'); if(f)f.onsubmit=e=>{e.preventDefault();Object.assign(state.query,Object.fromEntries(new FormData(f)));state.query.page=1;render();};
  document.querySelector('#prev')?.addEventListener('click',()=>{state.query.page--;render();}); document.querySelector('#next')?.addEventListener('click',()=>{state.query.page++;render();});
  document.querySelector('#create')?.addEventListener('click',()=>{document.querySelector('#action').innerHTML=ticketForm();bindTicket();}); bindTicket(); bindJira(); bindUsers();
}
function bindDetail(id){
  document.querySelector('#back').onclick=()=>{state.page='tickets';render();};
  document.querySelector('#edit')?.addEventListener('click',async()=>{document.querySelector('#action').innerHTML=ticketForm((await api('/tickets/'+id)).ticket);bindTicket(id);});
  const accept=document.querySelector('[data-feedback="accept"]'); if(accept)accept.onclick=()=>submitFeedback(id,Number(accept.dataset.prediction),'accept');
  const override=document.querySelector('[data-feedback="override"]'); if(override)override.onclick=()=>{const predictionId=Number(override.dataset.prediction);document.querySelector('#feedback-action').innerHTML=overrideForm(predictionId);bindOverride(id,predictionId);};
}
async function submitFeedback(ticketId,predictionId,decision,payload={}){try{await api(`/tickets/${ticketId}/feedback`,{method:'POST',body:JSON.stringify({prediction_id:predictionId,decision,...payload})});document.querySelector('.content').innerHTML=await detail(ticketId);bindDetail(ticketId);}catch(x){const o=document.querySelector('#feedback-action output');if(o)o.textContent=x.message;else alert(x.message);}}
function bindOverride(ticketId,predictionId){const f=document.querySelector('#override-form');if(!f)return;f.onsubmit=e=>{e.preventDefault();const x=Object.fromEntries(new FormData(f));submitFeedback(ticketId,predictionId,'override',{corrected_team:x.corrected_team,comment:x.comment});};}
function bindTicket(id){const f=document.querySelector('#ticket-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(f));p.created_hours=Number(p.created_hours);try{const r=await api(id?`/tickets/${id}`:'/tickets',{method:id?'PATCH':'POST',body:JSON.stringify(p)});if(id){document.querySelector('.content').innerHTML=await detail(id);bindDetail(id);}else{await api('/tickets/'+r.ticket.id+'/predict',{method:'POST'});document.querySelector('.content').innerHTML=await detail(r.ticket.id);bindDetail(r.ticket.id);}}catch(x){f.querySelector('output').textContent=x.message;}};}
function bindJira(){const f=document.querySelector('#jira');if(f)f.onsubmit=async e=>{e.preventDefault();const x=new FormData(f);try{const d=await api('/integrations/jira/import',{method:'POST',body:JSON.stringify({issue:{key:x.get('key'),fields:{summary:x.get('summary'),priority:{name:x.get('priority')},created_hours:Number(x.get('hours'))}}})});f.querySelector('output').textContent=`Saved ${d.ticket.jira_issue_key}.`;}catch(er){f.querySelector('output').textContent=er.message;}};}
function bindUsers(){document.querySelectorAll('.user').forEach(b=>b.onclick=async()=>{try{await api('/users/'+b.dataset.id,{method:'PATCH',body:JSON.stringify({role:document.querySelector(`[data-role="${b.dataset.id}"]`).value,disabled:b.dataset.disabled!=='true'})});render();}catch(e){alert(e.message);}});const f=document.querySelector('#new-user');if(f)f.onsubmit=async e=>{e.preventDefault();try{await api('/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(f)))});render();}catch(x){f.querySelector('output').textContent=x.message;}};}
render();
